### ISSUE TITLE
Strategy.bybit_reset_position_leverage_long() missing 1 required positional argument: 'max_leverage'

### ISSUE THREAD

**Issue by ilaykim** [donewiththedollar/directionalscalper#52]
Exception in thread Thread-20 (run_single_symbol):
Traceback (most recent call last):
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bot/directionalscalper/directionalscalper/core/strategies/bybit/multi/bybit_mfirsi_trend_rotator.py", line 234, in run_single_symbol
    self.bybit_reset_position_leverage_long(long_pos_qty, total_equity, best_ask_price, max_leverage)
TypeError: Strategy.bybit_reset_position_leverage_long() missing 1 required positional argument: 'max_leverage'
Futures balance: 267.63710647
symbols_allowed from config: None

**Comment by ilaykim** [comment]
**v2** _works_ btw
