### ISSUE TITLE
bybit_mfirsi_trend_rotator.py", line 234, in run_single_symbol - max_leverage

### ISSUE THREAD

**Issue by ilaykim** [donewiththedollar/directionalscalper#53]
File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bot/directionalscalper/directionalscalper/core/strategies/bybit/multi/**bybit_mfirsi_trend_rotator.py**", line 234, in run_single_symbol
    self.bybit_reset_position_leverage_long(long_pos_qty, total_equity, best_ask_price, max_leverage)
TypeError: Strategy.bybit_reset_position_leverage_long() missing 1 required positional argument: **'max_leverage'**
Exception in thread Thread-193 (run_single_symbol):
Traceback (most recent call last):
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bot/directionalscalper/directionalscalper/core/strategies/bybit/multi/bybit_mfirsi_trend_rotator.py", line 234, in run_single_symbol
    self.bybit_reset_position_leverage_long(long_pos_qty, total_equity, best_ask_price, max_leverage)
TypeError: Strategy.bybit_reset_position_leverage_long() missing 1 required positional argument: 'max_leverage'
Exception in thread Thread-195 (run_single_symbol):
Traceback (most recent call last):
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bot/directionalscalper/directionalscalper/core/strategies/bybit/multi/bybit_mfirsi_trend_rotator.py", line 234, in run_single_symbol
    self.bybit_reset_position_leverage_long(long_pos_qty, total_equity, best_ask_price, max_leverage)
TypeError: Strategy.bybit_reset_position_leverage_long() missing 1 required positional argument: 'max_leverage'
Futures balance: 436.80289062
symbols_allowed from config: None
Running for symbol (inside run_single_symbol method): MATICUSDT
Exception in thread Thread-196 (run_single_symbol):
Traceback (most recent call last):
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bot/directionalscalper/directionalscalper/core/strategies/bybit/multi/bybit_mfirsi_trend_rotator.py", line 234, in run_single_symbol
Exception in thread Thread-194 (run_single_symbol):
    self.bybit_reset_position_leverage_long(long_pos_qty, total_equity, best_ask_price, max_leverage)
Traceback (most recent call last):
  File "/home/bot/.pyenv/versions/3.11.0/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
TypeError: Strategy.bybit_reset_position_leverage_long() missing 1 required positional argument: 'max_leverage'

**Comment by donewiththedollar** [comment]
Resolved :) Thank you for pointing this out, I have been on a bug hunting binge creating more bugs 🥲
